# -*- coding: utf-8 -*-
"""Main

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-gb0LC4K97dHpTQ2yOq0M9bFpOePjQeQ
"""

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from sklearn.linear_model import LinearRegression
import joblib

app = FastAPI()

class TrainingData(BaseModel):
    X: list[float]
    y: list[float]

class PredictionData(BaseModel):
    X: list[float]

model = LinearRegression()

@app.post("/train/")
def train_model(data: TrainingData):
    try:
        X = data.X
        y = data.y
        model.fit(X, y)
        joblib.dump(model, "model.pkl")
        return {"message": "Model trained and saved successfully"}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/predict/")
def predict_value(data: PredictionData):
    try:
        model = joblib.load("model.pkl")
        X = data.X
        prediction = model.predict([X])
        return {"prediction": prediction[0]}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))