# -*- coding: utf-8 -*-
"""test_custom_transformers01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FgOQeuJm2Z_hjLDAR4FPInto6Pm-3eAM

CustomScaler
Verifies that the CustomScaler transformer correctly performs standard scaling on the data **texto en negrita**
"""

import numpy as np
from sklearn.datasets import load_iris
from transformers.custom_transformers import CustomScaler, CustomEncoder


def test_custom_scaler():

      # Ruta ficticia a la carpeta "data" en el sistema
    data_folder = 'C:\Users\Edgar F\Desktop\000MLOPS\02AmbientesVirtuales\my_project\data'

    # Load the data
    data = os.path.join(data_folder, 'heart.csv')

     X = data.data

     # Create an instance of the CustomScaler
     scaler = CustomScaler()

     # Fit the transformer to the data
     scaler.fit(X)

     # Transform the data using the CustomScaler
     X_scaled = scaler.transform(X)

     #  Make statements to verify the scale
     assert np.allclose(X_scaled.mean(axis=0), 0.0, atol=1e-7), "Scaling not performed correctly"
     assert np.allclose(X_scaled.std(axis=0), 1.0, atol=1e-7), "Scaling not performed correctly"