# -*- coding: utf-8 -*-
"""04_Verify_trained_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FgOQeuJm2Z_hjLDAR4FPInto6Pm-3eAM

# unit test to verify that a trained model exists after it has been saved
"""

import os
import pytest
from model_trainer import ModelTrainer


def test_model_existence():
    # Paso 1: Crear una instancia de ModelTrainer
    trainer = ModelTrainer()

    # Paso 2: Entrenar el modelo (esto es un ejemplo ficticio)
    model = trainer.train_model()

    # Paso 3: Guardar el modelo entrenado
    model_path = 'trained_models/my_model.pkl'
    trainer.save_model(model, model_path)

    # Paso 4: Verificar la existencia del archivo del modelo guardado
    assert os.path.exists(model_path), "Trained model file does not exist."